backend:
  name: github
  repo: slacklinebolognaasd/slacklinebolognaasd.github.io
  branch: master
  site_domain: fervent-carson-8473a7.netlify.app
media_folder: 'images'
collections:
  - name: '_pages_'
    label: 'Pages'
    files:
      - label: 'Home page'
        name: 'home'
        file: 'pages/pages-root-folder/index.md'
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "frontpage" }
          - { label: "Homepage", name: "homepage", widget: "hidden", default: true }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/index.html" }
          - { label: "Tab title", name: "title", widget: "string" }
          - {
              label: "Header",
              name: "header",
              widget: "object",
              fields: [
                { label: "Title", name: "title", widget: "string" },
                { label: "Image", name: "image_fullwidth", widget: "image" }
              ]
            }
          - {
              label: "First Box",
              name: "widget1",
              widget: "object",
              fields: [
                { label: "Url", name: "url", widget: "hidden", default: "/lezioni" },
                { label: "Title", name: "title", widget: "string" },
                { label: "Text", name: "text", widget: "string" },
                { label: "Image", name: "image", widget: "image" }
              ]
            }
          - {
              label: "Second Box",
              name: "widget2",
              widget: "object",
              fields: [
                { label: "Url", name: "url", widget: "hidden", default: "/lezioni" },
                { label: "Title", name: "title", widget: "string" },
                { label: "Text", name: "text", widget: "string" },
                { label: "Image", name: "image", widget: "image" }
              ]
            }
          - {
              label: "Third Box",
              name: "widget3",
              widget: "object",
              fields: [
                { label: "Url", name: "url", widget: "hidden", default: "/lezioni" },
                { label: "Title", name: "title", widget: "string" },
                { label: "Text", name: "text", widget: "string" },
                { label: "Image", name: "image", widget: "image" }
              ]
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: 'Chi siamo'
        name: 'chi-siamo'
        file: 'pages/chi-siamo.md'
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/chi-siamo/" }
          - {
              label: "Header",
              name: "header",
              widget: "object",
              fields: [
                { label: "Title", name: "title", widget: "string", required: false },
                { label: "Image", name: "image_fullwidth", widget: "image" }
              ]
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Tab title", name: "meta_title", widget: "string" }
          - {
              label: "Image",
              name: "image",
              widget: "object",
              required: false,
              fields: [
                { label: "Image", name: "title", widget: "image", required: false },
                { label: "Caption", name: "caption", widget: "string", required: false },
                { label: "Caption url", name: "caption_url", widget: "string", required: false }
              ]
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: 'Blog'
        name: 'blog'
        file: '_layouts/default-with-blog-header.html'
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
          - { label: "Tab title", name: "title", widget: "string" }
          - {
              label: "Header",
              name: "header",
              widget: "object",
              fields: [
                { label: "Title", name: "title", widget: "string", required: false },
                { label: "Image", name: "image_fullwidth", widget: "image" }
              ]
            }
          - { label: "Body", name: "body", widget: "hidden", default: "{{content}}" }
      - label: 'Spettacoli/eventi'
        name: 'spettacoli-eventi'
        file: 'pages/spettacoli-eventi.md'
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/spettacoli-eventi/" }
          - {
              label: "Header",
              name: "header",
              widget: "object",
              fields: [
                { label: "Title", name: "title", widget: "string", required: false },
                { label: "Image", name: "image_fullwidth", widget: "image" }
              ]
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Tab title", name: "meta_title", widget: "string" }
          - {
              label: "Image",
              name: "image",
              widget: "object",
              required: false,
              fields: [
                { label: "Image", name: "title", widget: "image", required: false },
                { label: "Caption", name: "caption", widget: "string", required: false },
                { label: "Caption url", name: "caption_url", widget: "string", required: false }
              ]
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: 'Lezioni'
        name: 'lezioni'
        file: 'pages/lezioni.md'
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/lezioni/" }
          - {
              label: "Header",
              name: "header",
              widget: "object",
              fields: [
                { label: "Title", name: "title", widget: "string", required: false },
                { label: "Image", name: "image_fullwidth", widget: "image" }
              ]
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Tab title", name: "meta_title", widget: "string" }
          - {
              label: "Image",
              name: "image",
              widget: "object",
              required: false,
              fields: [
                { label: "Image", name: "title", widget: "image", required: false },
                { label: "Caption", name: "caption", widget: "string", required: false },
                { label: "Caption url", name: "caption_url", widget: "string", required: false }
              ]
            }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: 'Contattaci'
        name: 'contattaci'
        file: 'pages/contattaci.md'
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/contattaci/" }
          - {
              label: "Header",
              name: "header",
              widget: "object",
              fields: [
                { label: "Title", name: "title", widget: "string", required: false },
                { label: "Image", name: "image_fullwidth", widget: "image" }
              ]
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Tab title", name: "meta_title", widget: "string" }
          - {
              label: "Image",
              name: "image",
              widget: "object",
              required: false,
              fields: [
                { label: "Image", name: "title", widget: "image", required: false },
                { label: "Caption", name: "caption", widget: "string", required: false },
                { label: "Caption url", name: "caption_url", widget: "string", required: false }
              ]
            }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: 'blog'
    label: 'Blog posts'
    folder: '_posts/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog-page" }
      - { label: "Categories", name: "categories", widget: "hidden", default: ["blog"] }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Teaser", name: "teaser", widget: "string" }
      - { label: "Search engine teaser", name: "meta_teaser", widget: "string" }
      - {
          label: "Image",
          name: "image",
          widget: "object",
          required: false,
          fields: [
            { label: "Image", name: "title", widget: "image", required: false },
            { label: "Caption", name: "caption", widget: "string", required: false },
            { label: "Caption url", name: "caption_url", widget: "string", required: false }
          ]
        }
      - { label: "Body", name: "body", widget: "markdown" }
